name: URLChecker
on: [pull_request]

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2
    - name: Test GitHub Action
      uses: urlstechie/urlchecker-action@0.0.27
      with: 
        file_types: .md
        white_listed_files: docs
